-- LearnTracker 数据库建表脚本
-- 数据库: PostgreSQL

-- 1. 用户表
CREATE TABLE "user" (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) NOT NULL UNIQUE,
    email varchar(100) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    deleted integer DEFAULT 0
);

-- 2. 学习资源表
CREATE TABLE resource (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL REFERENCES "user"(id),
    title varchar(200) NOT NULL,
    description text,
    url varchar(500),
    category varchar(50),
    priority integer DEFAULT 2,
    status varchar(20) DEFAULT 'todo',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    deleted integer DEFAULT 0
);

-- 3. 标签表
CREATE TABLE tag (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL REFERENCES "user"(id),
    name varchar(50) NOT NULL,
    color varchar(20) DEFAULT '#000000',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    deleted integer DEFAULT 0
);

-- 4. 资源标签中间表（多对多关系）
CREATE TABLE resource_tag (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    resource_id bigint NOT NULL REFERENCES resource(id),
    tag_id bigint NOT NULL REFERENCES tag(id)
);

-- 5. 笔记表
CREATE TABLE note (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    resource_id bigint REFERENCES resource(id),
    user_id bigint NOT NULL REFERENCES "user"(id),
    content text NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    deleted integer DEFAULT 0
);